### ISSUE TITLE
no source

### ISSUE THREAD

**Issue by giuseppeM99** [IATAdev/IATA-bot#1]
there are no source aviable
pls commit a code
**in case of fire**
git commit
git pull
**save hdd data**

**Comment by MarcoBuster** [comment]
What? The source code will added soon, when the bot it's aviable.

**Comment by lollofra** [comment]
LOL MONA

**Comment by MarcoBuster** [comment]
@lollofra Please speak only in English, this is a international chat.
What do you mean?
